import { Navbar } from "../../../../libs/ui/src/components/Navbar";
import "./globals.css";

import { ThemeProvider } from "../../../../libs/ui/src/index";

export const metadata = {
  title: "Welcome",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar source="ecommerce" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
