import Navbar from "../component/Navbar";
import "./global.css";
import { ThemeProvider } from "@ui";

export const metadata = {
  title: "Welcome to ecommerce",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
