import { Navbar } from "../../../../libs/ui/src/components/Navbar";
import { Footer } from "../../../../libs/ui/src/components/Footer";


import { LocaleButton } from "../../../../libs/ui/src/components/ui/buttons/geoButton";

import { Input } from "../../../../libs/ui/src/components/input/index";
import { ThemeToggle } from "../../../../libs/ui/src/components/ui/themeTogglerButton";
import { ThemeProvider } from "../../../../libs/ui/src/hooks/ThemeProvider";
import { Button } from "../../../../libs/ui/src/components/button/index";

import "./globals.css";

import {
  Book,
  Component,
  InfoIcon,
  Menu,
  Phone,
  Search,
  Shield,
  Smartphone,
  User2,
} from "lucide-react";
import Link from "next/link";
import { FaHeart, FaShoppingBag } from "react-icons/fa";

export const metadata = {
  title: "Welcome",
  description: "Generated by create-nx-workspace",
};

const navLinks = [
  {
    containerClassName: "flex justify-center items-center",
    className: "flex justify-center items-center gap-x-1 text-sm",
    iconClassName: "relative",
    buttonText: "About-us",
    type: "link",
    href: "/about",
    action: "",
    icon: <InfoIcon size={16} />,
    counterText: "",
    showCounter: false,
  },
  {
    containerClassName: "flex justify-center items-center",
    className: "flex justify-center items-center gap-x-1 text-sm",
    iconClassName: "relative",
    buttonText: "Contact-us",
    type: "link",
    href: "/contact-us",
    action: "",
    icon: <Phone size={16} />,
    counterText: "",
    showCounter: false,
  },
  {
    containerClassName: "flex justify-center items-center",
    className: "flex justify-center items-center gap-x-1 text-sm",
    iconClassName: "relative",
    buttonText: "Blogs",
    type: "link",
    href: "/blogs",
    action: "",
    icon: <Book size={16} />,
    counterText: "",
    showCounter: false,
  },
  {
    containerClassName: "flex justify-center items-center",
    className: "flex justify-center items-center gap-x-1 text-sm",
    iconClassName: "relative",
    buttonText: "MStore support 24/7Hr",
    type: "link",
    href: "/support",
    action: "",
    icon: <Shield size={16} />,
    counterText: "",
    showCounter: false,
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Navbar
            source="ecommerce"
            className="w-screen h-[100px] flex justify-center items-center fixed top-0 dark:bg-neutral-900 bg-neutral-100 z-[9999]"
            containerClassName="w-full flex flex-col justify-center items-center"
            hideNavAtRoutes={["/admin", ""]}
            topNav={true}
            topNavContent={
              <div className=" w-full h-[40px] bg-green-600 flex justify-center items-center">
                <div
                  className="lg:w-11/12 md:w-11/12 w-11/12 flex justify-between items-center
                "
                >
                  <div className="flex justify-center items-center gap-x-1 font-medium">
                    <Smartphone size={16} className="" />
                    <div className="text-sm">Download App</div>
                  </div>

                  <div className="h-full md:flex hidden justify-center items-center gap-x-4">
                    {navLinks.map((d, index) => {
                      return (
                        <Button
                          key={index}
                          containerClassName={d.containerClassName}
                          className={d.className}
                          iconClassName={d.iconClassName}
                          buttonText={d.buttonText}
                          type={"link"}
                          href={d.href}
                          action={d.action}
                          icon={d.icon}
                          counterText={d.counterText}
                          showCounter={d.showCounter}
                        />
                      );
                    })}

                    {/* <LocaleButton /> */}
                  </div>

                  <div className="md:hidden flex">
                    <Button
                      containerClassName="flex justify-center items-center"
                      className="flex justify-center items-center gap-x-1 text-md"
                      iconClassName="relative"
                      buttonText=""
                      type="button"
                      href={""}
                      action={""}
                      icon={<Menu size={16} />}
                      counterText=""
                      showCounter={false}
                    />
                  </div>
                </div>
              </div>
            }
            mainNav={true}
            mainNavContent={
              <div className="w-full h-[60px] flex justify-center items-center border-b dark:border-neutral-600 border-neutral-400">
                <div className="lg:w-11/12 md:w-11/12 w-11/12 h-full flex justify-between items-center">
                  <div className="lg:w-3/12 h-full flex justify-start items-center gap-x-4">
                    <Link
                      href={"/"}
                      className="font-medium dark:text-white text-black"
                    >
                      MStore
                    </Link>

                    {/* <button className="flex justify-center items-center gap-x-1 dark:text-white text-black">
                      <MapPin />
                      <div className="flex justify-center items-center ">
                        <input className="" placeholder="Enter pin code" />
                        <div className="flex flex-col">
                          <div>Find Us</div>{" "}
                          <div className="text-xs">Near you</div>
                        </div>
                      </div>
                    </button> */}
                  </div>

                  <div className=" h-full flex-1 xl:flex lg:hidden justify-center items-center hidden">
                    <Input
                      type="select"
                      containerClassName="w-[200px] relative"
                      label=""
                      iconVisibility={true}
                      icon={<Component />}
                      inputType="text"
                      placeholder="All categories"
                      optionData={
                        <>
                          <option value={"all-catgeories"}>All categories</option>
                        </>
                      }
                      inputContainerClassName="w-full "
                      iconClassName=""
                      labelClassName="block mb-2.5 text-sm font-medium text-heading"
                      className={`ps-12 p-3 rounded-tl-md rounded-bl-md bg-green-600 text-white w-full appearance-none`}
                      phoneCode={false}
                      value={""}
                      name=""
                      onChange={""}
                    />

                    {/*  search bar */}
                    <Input
                      type="input"
                      containerClassName="flex-1 relative"
                      label=""
                      labelClassName="block mb-2.5 text-sm font-medium text-heading"
                      iconVisibility={true}
                      icon={
                        <Search className="dark:text-neutral-400 text-neutral-600" />
                      }
                      inputType="text"
                      placeholder="Search Category,Brands,looks,etc"
                      optionData={<></>}
                      inputContainerClassName=""
                      iconClassName=""
                      className={`flex-1 block ps-12 pe-3 py-3 dark:bg-neutral-700 bg-neutral-200 border dark:border-neutral-600 border-neutral-400 text-heading text-sm rounded-br-md rounded-tr-md focus:ring-brand focus:border-brand shadow-xs placeholder:dark:text-neutral-400 placeholder:text-neutral-600 text-left`}
                      phoneCode={false}
                      value={""}
                      name=""
                      onChange={""}
                    />
                  </div>

                  <div className="lg:w-[400px] md:w-1/2 w-1/2 h-full gap-x-4 flex justify-end items-center">
                    <ThemeToggle />

                     <Button
                      containerClassName="h-full flex justify-center items-center"
                      className="h-full md:flex hidden justify-center items-center gap-x-1 text-md dark:text-white text-black"
                      iconClassName="relative p-1 flex justify-center items-center border rounded-full"
                      buttonText="Sign-in"
                      type="link"
                      href={"/auth/login"}
                      action={""}
                      icon={<User2 size={16} />}
                      counterText=""
                      showCounter={false}
                    />

                    <Button
                      containerClassName="h-full flex justify-center items-center"
                      className="h-full flex justify-center items-center gap-x-1 text-md dark:text-white text-black"
                      iconClassName="relative p-1 flex justify-center items-center"
                      buttonText="Wishlist"
                      type="button"
                      href={""}
                      action={""}
                      icon={<FaHeart size={16} />}
                      counterText="4"
                      showCounter={true}
                    />

                    <Button
                      containerClassName="h-full flex justify-center items-center"
                      className="h-full flex justify-center items-center gap-x-1 text-md dark:text-white text-black"
                      iconClassName="relative p-1 flex justify-center items-center"
                      buttonText="Cart"
                      type="button"
                      href={""}
                      action={""}
                      icon={<FaShoppingBag size={16} />}
                      counterText="2"
                      showCounter={true}
                    />
                  </div>
                </div>
              </div>
            }
          />
          {children}
          <Footer className={"w-screen h-[40vh] dark:bg-neutral-800 bg-neutral-100 border-t dark:border-neutral-600 border-neutral-600 dark:text-white text-black flex justify-center items-center"} />
        </ThemeProvider>
      </body>
    </html>
  );
}
