// import './global.css';

import Navbar from "../../../../libs/ui/src/components/Navbar"

export const metadata = {
  title: 'Welcome to portfolio-web',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
         <Navbar source="portfolio" />
        {children}
        
        </body>
    </html>
  )
}
