import "./global.css";
import { Navbar } from "../../../libs/ui/src/components/Navbar";

export const metadata = {
  title: "Welcome to restaurant",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar
          source="restaurant"
          className="w-screen h-[100px] flex justify-center items-center fixed top-0"
          containerClassName="w-full flex flex-col justify-center items-center"
          hideNavAtRoutes={["/admin", ""]}
          topNav={true}
          topNavContent={
            <div className="w-full flex justify-center items-center h-[40px] bg-yellow-600">
              <div className="lg:w-10/12 md:w-11/12 w-full ">LOGO</div>
            </div>
          }
          mainNav={true}
          mainNavContent={
            <div className="w-full h-[60px] flex justify-center items-center">
              <div className="lg:w-10/12 md:w-11/12 w-full h-full">POGO</div>
            </div>
          }
        />
        {children}
      </body>
    </html>
  );
}
